### ISSUE TITLE
i ran the container, what i need to do now? how can i check the server

### ISSUE THREAD

**Issue by refaeldimri** [Craicerjack/apache-flask#10]
hello.
i wrote my issue in the title

TNX

**Comment by carlostighe** [comment]
Hi. Then you should go to 0.0.0.0 in your browser and see your flask app

**Comment by refaeldimri** [comment]
> Hi. Then you should go to 0.0.0.0 in your browser and see your flask app

I do not see. I see "internal server error".
Why?

**Comment by carlostighe** [comment]
in your terminal run `docker logs <docker_image_name>` and it will output the issue

**Comment by refaeldimri** [comment]
> in your terminal run `docker log <docker_image_name>` and it will output the issue

There is no command "docker log"

**Comment by carlostighe** [comment]
so that should be `logs` not `log`


So there is something wrong with your flask app. 
The logs of the flask app are linked to the docker image logs. 
How did you run the docker image? 
Are you on the command line or using some gui? 
How do you access docker logs in the environment you are using?

**Comment by refaeldimri** [comment]
I ran docker logs apache spark and i got "no such container: apache-spark.

I ran docker image like writted: docker build -t apache-spark.

I ran the container docker-compose up -d

I am on command line on linux.


> so that should be `logs` not `log`
> 
> So there is something wrong with your flask app.
> The logs of the flask app are linked to the docker image logs.
> How did you run the docker image?
> Are you on the command line or using some gui?
> How do you access docker logs in the environment you are using?

Tnx

**Comment by refaeldimri** [comment]
I ran docker logs apache spark and i got "no such container: apache-spark.

I ran docker image like writted: docker build -t apache-spark.

I ran the container docker-compose up -d

I am on command line on linux.

**Comment by carlostighe** [comment]
`docker container ls`   
will give you a list of container details. You should be able to find the name of your container there. 

Do you have a flask app in the same folder as the `Docker` file? 
The command to build the image is `docker build -t <image_tag> .`   
The period at the end of that command is important. It says to use this folder as the source of the image. 


This repo and image is for running flask using apache as a server.  
It is not for running apache spark.

**Comment by refaeldimri** [comment]
> `docker container ls`
> will give you a list of container details. You should be able to find the name of your container there.
> 
> Do you have a flask app in the same folder as the `Docker` file?
> The command to build the image is `docker build -t <image_tag> .`
> The period at the end of that command is important. It says to use this folder as the source of the image.
> 
> This repo and image is for running flask using apache as a server.
> It is not for running apache spark.

What is <image_tag>?
Yes. I know it is flask, i just confused. Tnx friend

**Comment by refaeldimri** [comment]
> > `docker container ls`
> > will give you a list of container details. You should be able to find the name of your container there.
> > Do you have a flask app in the same folder as the `Docker` file?
> > The command to build the image is `docker build -t <image_tag> .`
> > The period at the end of that command is important. It says to use this folder as the source of the image.
> > This repo and image is for running flask using apache as a server.
> > It is not for running apache spark.
> 
> What is <image_tag>?
> Yes. I know it is flask, i just confused. Tnx friend

What is flask app?

**Comment by carlostighe** [comment]
Image tag is the name you give to the docker image

**Comment by refaeldimri** [comment]
i removed all and then i ran this command:
1. sudo docker build -t apache-flask .
2. docker run -d -p 80:80 --name container-apache apache-flask

is it ok?
it still does not work when i type 0.0.0.0 in my browser :\

**Comment by carlostighe** [comment]
What are you trying to run? 

You should have a folder structure like this repo. 

You're best bet would be to download this repo. Go into it and then run the docker commands.

**Comment by refaeldimri** [comment]
Sure, i downloaded this repo, open a terminal and run the commands i writted.

Like i told u i build a image and run container, the browser cant connect to server

I just need to implement web server with python apach and docker.

**Comment by carlostighe** [comment]
- Download the repo
- `cd` into the app directory
- build the image: `docker build -t apache-flask .`
- `docker run -dp 80:80 --name flask apache-flask` 
- visit 0.0.0.0
- `docker container ls` - see what containers are running
- `docker logs flask` - should output any errors.

**Comment by refaeldimri** [comment]
Tnx, i try and let u know. I appreciate.

**Comment by refaeldimri** [comment]
i did it.
when i run command: docker logs <container name> i got the error:

"AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message"

**Comment by carlostighe** [comment]
Thats just a warning not an error. 
I just ran through the process just now and going to `0.0.0.0` gives me the following:
![flask](https://user-images.githubusercontent.com/4867797/94907965-e21ca400-0498-11eb-909b-882b64225bc3.png)

**Comment by refaeldimri** [comment]
> Thats just a warning not an error.
> I just ran through the process just now and going to `0.0.0.0` gives me the following:
> ![flask](https://user-images.githubusercontent.com/4867797/94907965-e21ca400-0498-11eb-909b-882b64225bc3.png)

Maybe i have to install another something on my comuter?

**Comment by carlostighe** [comment]
When you run docker build do you get output?  

![docker_build_flask](https://user-images.githubusercontent.com/4867797/94930685-b01e3880-04be-11eb-9ad0-cade174b26e0.png)

when i run docker container ls i get this output
![container_ls](https://user-images.githubusercontent.com/4867797/94930844-ed82c600-04be-11eb-82de-db87372f08b0.png)

**Comment by refaeldimri** [comment]
Yes, i get this output

**Comment by carlostighe** [comment]
so what do you get when you open your browser and go to `http://0.0.0.0`?

**Comment by refaeldimri** [comment]
this msg

![Untitled](https://user-images.githubusercontent.com/45371684/94934389-54f74080-04d4-11eb-869c-3c1af4567a3a.png)

**Comment by carlostighe** [comment]
okay, I didnt have the apache logs linked to the container logs. 
Ive just done a push there so if you do a new pull, run through it again
and this time `docker logs` should output any errors.

**Comment by refaeldimri** [comment]
I did
these errors:

![Untitled](https://user-images.githubusercontent.com/45371684/94991730-97c91f00-058d-11eb-90f2-1fcf9863c0b9.png)

**Comment by carlostighe** [comment]
Is there more to that stack trace?

**Comment by refaeldimri** [comment]
yes
![ללא שם](https://user-images.githubusercontent.com/45371684/95176043-faf0c680-07c4-11eb-810d-bf8e121aeb92.gif)

**Comment by carlostighe** [comment]
There you go `TemplateNotFound: index.html` - thats the error. 

Is `index.html` in `app/templates/` 

It might be an idea to get the flask app running outside of docker then once it is build the image and run it via docker.

**Comment by refaeldimri** [comment]
there is file index.html in app/templates. yes
i do not understand. what to do?

i used the repo like i downloaded it, i did not change to location of the file. yes?

**Comment by carlostighe** [comment]
I dont know. Its not finding index.html so...
If you get the flask app running locally.
Make a virtualenv, install the requirements, and run the app. 
You can debug in then, and once its working build the docker image again.

**Comment by refaeldimri** [comment]
Maybe u have tutorial or code:
Http server and client by apache, client sent string to server ang get
string, no html.
Thats all i need

**Comment by carlostighe** [comment]
I don't but there are plenty on the web. Best of luck
