### ISSUE TITLE
debian:latest in Dockerfile to correct

### ISSUE THREAD

**Issue by syndrael** [Craicerjack/apache-flask#11]
Hello,
We can't build anymore with debian:latest 
FROM debian:buster 
works, et does the job :-)

**Comment by carlostighe** [comment]
Can you provide any further details. OS, errors etc. I cannot replicate the error

**Comment by carlostighe** [comment]
Updated to 
`FROM debian:bullseye-slim`

**Comment by syndrael** [comment]
👍
