### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by empereira** [Craicerjack/apache-flask#5]
hello @Craicerjack,

I was setting up an application in flask + wsgi on the docker and I came across your settings. They helped me a lot.

After loading the containers and trying to access them externally, error 404 is occurring.

You inform the following: "# The commands below get apache running but there are issues accessing it online"

Can it be related to that?

**Comment by carlostighe** [comment]
Hi,

Okay so a couple of questions. 

> After loading the containers  
 - How many containers do you have?   
 - Where are the containers loaded? On a server? Locally?  

>  Trying to access them externally?  
 - Again I suppose the question is where are the containers running and where are you trying to access them from?  

Regarding the commented code - no that is commented out for the reason that it didnt work. The `CMD` that isnt commented is the one that should work.

**Comment by carlostighe** [comment]
Closing this as there has been no response since march
